### ISSUE TITLE
Problem to see my Instagram feed

### ISSUE THREAD

**Issue by matlecleuziat** [h0ke/jquery-embedagram#17]
Hi,
Thank you for your html code, but i have a problem to show my instagram feed.
You can see it here : http://www.mandeh.fr/gallery.html

Could you help me to resolve this problem ?

Thanks in advance,

Mathieu

**Comment by h0ke** [comment]
Hey Mathieu:

Everything looks good to me except you have left the brackets around your instagram id.

```
			    <script type="text/javascript">
			        $(document).ready(function() {
			            $('#slideshow').embedagram({
			                    instagram_id: <1464658551>
			                });
			        });
			    </script>
```

The `<1464658551>` should be `1464658551`

**Comment by matlecleuziat** [comment]
Hi !
Thank you for your quickly feedback.
I have deleted the brackets around my instagram ID but i have always this problem.. :(

Thanks a lot for your help! 

Mat

**Comment by h0ke** [comment]
You're getting close. :smile: 

It looks like the jquery file you're pointing to doesn't exist.

```
<script type="text/javascript" src="assets/js/jquery-1.6.1.min.js"></script>
			    <script type="text/javascript" src="assets/js/jquery-embedagram.pack.js"></script>
			    <script type="text/javascript">
			        $(document).ready(function() {
			            $('#slideshow').embedagram({
			                    instagram_id: 1464658551
			                });
			        });
			    </script>
			    <!-- http://embedagram.com/plugin.php -->
```

http://www.mandeh.fr/assets/js/jquery-1.6.1.min.js

**Comment by matlecleuziat** [comment]
Thank you!!
I think that I'm not lucky...
I have fixed the jquery file... but my page is empty...

**Comment by h0ke** [comment]
It looks like you have other javascript errors on your page. If you look in the developer tools of your browser, you can see what i mean.

https://www.dropbox.com/s/2bdi1q1g8lvrkhl/Screenshot%202015-03-20%2014.26.16.png?dl=0

**Comment by matlecleuziat** [comment]
Arg....
Have you an idea to resolve this error of JS ?

Thanks

**Comment by kizoso** [comment]
Hi,
Thank you for embedagram, i like it, and it is easy to setup it. But now i have a problem. First time i setup it, and it works, but suddenly the block with photos disappeared. I try it on another id, and it works. I can't understand what is wrong.

You can see it here : http://kizoso.ru/template/my-embedagram-problem/

Could you help me to resolve this problem ?

Thanks in advance,

Kizoso

**Comment by h0ke** [comment]
Hey @kizoso 

I just looked at the link you shared and it seems to be working.

Am I looking at the right thing?

**Comment by kizoso** [comment]
@h0ke Thank you so much for your quick answer! 
It was my problem!
The problem was - user changed password without warning me. 
He clicked again "lets get started" and everything works now!
