### ISSUE TITLE
server side error from embedagram.com 

### ISSUE THREAD

**Issue by jackpilowsky** [h0ke/jquery-embedagram#18]
I'm getting a server side error on the JSON page:

http://embedagram.com/e/plugin/222294426/?callback=jQuery18108572395716328174_1430937682949&thumb_width=100&wrap_tag=li&limit=6&link_type=web&_=1430937683530

The error reads:

Warning: Invalid argument supplied for foreach() in /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php:61) in /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php on line 97
jQuery18108572395716328174_1430937682949({"html":""})64.13.192.156

**Comment by h0ke** [comment]
This can happen when embedagram is no longer authorized by your account.

Head over to embedagram.com and click on the 'let's get started' link.

**Comment by jackpilowsky** [comment]
That did the trick. 

I think the client must have revoked access accidently

**Comment by h0ke** [comment]
Awesome.
