### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < http://embedagram.com/e/plugin/

### ISSUE THREAD

**Issue by cojaco** [h0ke/jquery-embedagram#19]
Hi,

the embedagram plugin has stopped working.
Since two days or so the instagram Images are not displayed anymore.

The error in devtools is:

Uncaught SyntaxError: Unexpected token < http://embedagram.com/e/plugin/11008114/?callback=jQueryxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxx&thumb_width=155&wrap_tag=li&limit=20&link_type=web&_=xxxxxxxxxxx

when I call the url I get:

Warning: Invalid argument supplied for foreach() in /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php:61) in /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/plugin.php on line 97
jQuery18105638088386040181_1447670363121({"html":""})

**Comment by h0ke** [comment]
Hey, sorry about that.

This sometimes happen when embedagram loses permission to fetch an account's data. Could you reauthorize please.

Go to http://embedagram.com/ and click '...let's get started'.

**Comment by cojaco** [comment]
jup, that was it, thx a lot.
