### ISSUE TITLE
Display number of likes 

### ISSUE THREAD

**Issue by bravo14** [h0ke/jquery-embedagram#20]
Is it possible to display the number of likes from the data-likes `attribute

**Comment by h0ke** [comment]
Could you clarify what you mean by display?

The like count is made available for you to display as you see fit.

**Comment by fourroses666** [comment]
I think bravo14 would like the same as I do. 
Show the number of likes somewhere below or on the images.

**Comment by h0ke** [comment]
Closing as I haven't heard back from @bravo14 ...
