### ISSUE TITLE
empty boxes

### ISSUE THREAD

**Issue by extractjan** [h0ke/jquery-embedagram#21]
Hi,
Im getting empty boxes from different instagram accounts,
and found this error-message in the html source:
"Invalid argument supplied for foreach() in /nfs/c01/h09/mnt/33724/domains/embedagram.com/02-25-2014/e/widget.php"
(you can google it, there are some more sites with this error)

any idea, what the reason could be?

thanks
jan

**Comment by h0ke** [comment]
Hey Jan:

Can you revoke and re-auth through the homepage's "let's get started" link?

**Comment by h0ke** [comment]
Hey Jan:

I tracked down the bug that was probably causing your error. Please try again.

Thanks!

**Comment by extractjan** [comment]
Hi,

thanks for answering and helping.
but …. now i get a "file not found error" (in german ,-):

Fehler: Datei nicht gefunden

Die Dateien unter /e/widget/3057352478/?css=//mysite.com/embedagram.css konnten nicht gefunden werden.


(I had to use another application instead (for different reasons), and so no time for further testing … sorry.)

Thanks !
Jan

**Comment by h0ke** [comment]
Not a problem. Thanks for giving it a try.
