### ISSUE TITLE
How to show the Likes?

### ISSUE THREAD

**Issue by fourroses666** [h0ke/jquery-embedagram#22]
Hi h0ke, thanks allot for your work on this.

It works great for the images but the are some items I'd like to add to it.
Reading the issues and closed issues it should be possible to show the likes count (data-likes)?
And is there a way to show the date and description? 
_I'm not using the carouselslider, I'm styling it myself._

This is what would be my wish;
![example](https://cloud.githubusercontent.com/assets/523389/15319536/9ae373d4-1c2b-11e6-92f3-171af6182747.png)

**Comment by h0ke** [comment]
Hello... I'm not planning on making any changes to the jquery plugin. The likes are available on the element that is passed back. So you can access using whatever javascript makes most sense.

Thanks!
